apiVersion: v1
kind: Pod
metadata:
  name: pulsar-admin
spec:
  containers:
    - args:
        - bin/pulsar-admin
      command:
        - sh
        - -c
      env:
        - name: webServiceUrl
          valueFrom:
            configMapKeyRef:
              key: webServiceUrl
              name: pulsar-config
        - name: brokerServiceUrl
          valueFrom:
            configMapKeyRef:
              key: brokerServiceUrl
              name: pulsar-config
      image: apachepulsar/pulsar:latest
      name: pulsar-admin

