apiVersion: v1
kind: Pod
metadata:
  name: pulsar-admin
spec:
  containers:
    - image: apachepulsar/pulsar:latest
      name: pulsar-admin
      ports:
        - containerPort: 8080
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi

