apiVersion: v1
kind: Service
metadata:
  labels:
    app: open-api-doc
  name: open-api-doc
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: open-api-doc
  type: ClusterIP

