apiVersion: v1
kind: Pod
metadata:
  name: pulsar-admin
spec:
  containers:
    - args:
        - bin/pulsar-admin
        - some-arguments
      command:
        - /bin/bash
        - -c
      env:
        - name: PULSAR_ADMIN_CONFIG
          valueFrom:
            configMapKeyRef:
              key: config-key
              name: pulsar-admin-config
      image: apachepulsar/pulsar:latest
      name: pulsar-admin-container

