apiVersion: rbac/v1
kind: ClusterRole
metadata:
  name: config-viewer-role
rules:
  - apiGroups:
      - machine.crit.sh
    resources:
      - configs
      - configs/status
    verbs:
      - get
      - list

