apiVersion: v1
kind: Service
metadata:
  name: simple-app-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: SimpleApp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SimpleApp
  template:
    metadata:
      labels:
        app: SimpleApp
    spec:
      containers:
        - image: nginx:1.14.2
          name: simple-app-container
          ports:
            - containerPort: 8080

