apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pulsar-admin
  name: pulsar-admin
spec:
  containers:
    - image: apachepulsar/pulsar-all:latest
      name: pulsar-admin
      ports:
        - containerPort: 8080

