apiVersion: v1
kind: Pod
metadata:
  name: pulsar-admin
spec:
  containers:
    - command:
        - /bin/sh
        - -c
        - /pulsar/bin/pulsar-admin ${webServiceUrl} --admin-url ${brokerServiceUrl}
      env:
        - name: webServiceUrl
          valueFrom:
            configMapKeyRef:
              key: WEB_SERVICE_URL
              name: pulsar-admin-config
        - name: brokerServiceUrl
          valueFrom:
            configMapKeyRef:
              key: BROKER_SERVICE_URL
              name: pulsar-admin-config
      image: apachepulsar/pulsar:latest
      name: pulsar-admin
      resources:
        limits:
          memory: 1Gi
        requests:
          memory: 512Mi
  initContainers:
    - command:
        - /bin/sh
        - -c
        - source /pulsar/conf/envfile
      image: alpine
      name: init-config
      volumeMounts:
        - mountPath: /pulsar/conf
          name: config-volume
  volumes:
    - configMap:
        name: pulsar-admin-config
      name: config-volume

