apiVersion: v1
kind: Pod
metadata:
  name: pulsar-admin
spec:
  containers:
    - args:
        - -c
        - bin/pulsar-admin
      command:
        - /bin/sh
      image: apachepulsar/pulsar:latest
      name: pulsar-admin

