apiVersion: v1
kind: Pod
metadata:
  name: pulsar-admin
spec:
  containers:
    - args:
        - -c
        - bin/pulsar-admin
      command:
        - /bin/bash
      env:
        - name: webServiceUrl
          valueFrom:
            configMapKeyRef:
              key: webServiceUrl
              name: pulsar-config
        - name: brokerServiceUrl
          valueFrom:
            configMapKeyRef:
              key: brokerServiceUrl
              name: pulsar-config
      image: apachepulsar/pulsar:latest
      name: pulsar-admin
      resources:
        limits:
          memory: 512Mi
        requests:
          memory: 256Mi

