apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
    - command:
        - /bin/sh
        - -c
        - echo Hello, World!
      image: nginx
      name: example-container

