metadata:
  name: simple-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: MyApp
kind: Service
apiVersion: v1
---
metadata:
  name: simple-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: MyApp
  template:
    metadata:
      labels:
        app: MyApp
    spec:
      containers:
        - name: myapp-container
          image: nginx:1.14.2
          ports:
            - containerPort: 8080
kind: Deployment
apiVersion: apps/v1

